### ISSUE TITLE
Remove multi-category documents 

### ISSUE THREAD

**Issue by ParthKolekar** [AadityaNair/LDA-with-Deep-Learning#4]
Because of #1 we need to remove documents from TRAINING and TESTING sets which have multiple categories. 

```
In [14]: sum(map(lambda x: len(rt.categories(x)) != 1, filter(lambda x: x.startswith('train'), rt.fileids())))
Out[14]: 1192

In [15]: sum(map(lambda x: len(rt.categories(x)) != 1, filter(lambda x: x.startswith('test'), rt.fileids())))
Out[15]: 436
```

We lose those many documents, which should be ok, I guess.

**Comment by AadityaNair** [comment]
According to Ghosh, we already have too less documents to work with.
Also, what does it matter? we are not working with these categories. we are working with the ones generated by LDA.

**Comment by ParthKolekar** [comment]
So, apparently there is no need to retrain LDA.
